# Basic manipulations of your dataframe

### How can we add a column, delete a column, rename columns etc.?

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('https://github.com/wortell-smart-learning/python-data-fundamentals/raw/main/data/most_voted_titles_enriched.csv')

In [3]:
df.head(3)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,...,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
0,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,...,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...
1,tt0012349,movie,The Kid,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,...,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...
2,tt0013442,movie,Nosferatu,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,...,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...

### Notice that we don't see all columns when doing `df.head()` that's annoying.<br>Let's first check some of the standard settings and then change them:

In [4]:
pd.options.display.max_columns

20

### This means only 20 columns will be shown, but our dataframe has 26 columns. Let's change this setting:

In [5]:
pd.options.display.max_columns = 50

### Let's say we don't like primary Title column, let's delete it

In [6]:
df.drop(columns=['primaryTitle']).head(3)

,tconst,titleType,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url
0,tt0010323,movie,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,Horror,Mystery,https://www.imdb.com/title/tt0010323,8.1,57097,NaN,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...
1,tt0012349,movie,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,Drama,Family,https://www.imdb.com/title/tt0012349,8.3,112377,NaN,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...
2,tt0013442,movie,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,Horror,NaN,https://www.imdb.com/title/tt0013442,7.9,88440,NaN,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...

### Let's now add a column that takes the metascore and divides it by 10

In [13]:
df['new_metascore'] = df['metascore'] / 10.
df.head(3)

,tconst,titleType,primaryTitle,originalTitle,isAdult,start_year,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url,new_metascore
0,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,Horror,Mystery,https://www.imdb.com/title/tt0010323,8.1,57097,NaN,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...,NaN
1,tt0012349,movie,The Kid,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,Drama,Family,https://www.imdb.com/title/tt0012349,8.3,112377,NaN,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...,NaN
2,tt0013442,movie,Nosferatu,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,Horror,NaN,https://www.imdb.com/title/tt0013442,7.9,88440,NaN,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...,NaN

### If we want to rename a column, we can use `.rename()`

In [16]:
df.rename(columns={'startYear': 'start_year'}).head(3)

,tconst,titleType,primaryTitle,originalTitle,isAdult,start_year,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url,new_metascore
0,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,Horror,Mystery,https://www.imdb.com/title/tt0010323,8.1,57097,NaN,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...,NaN
1,tt0012349,movie,The Kid,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,Drama,Family,https://www.imdb.com/title/tt0012349,8.3,112377,NaN,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...,NaN
2,tt0013442,movie,Nosferatu,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,Horror,NaN,https://www.imdb.com/title/tt0013442,7.9,88440,NaN,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...,NaN

### But we haven't assigned it yet back to the df variable, it's still called startYear

In [18]:
df.head(3)

,tconst,titleType,primaryTitle,originalTitle,isAdult,start_year,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url,new_metascore
0,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,Horror,Mystery,https://www.imdb.com/title/tt0010323,8.1,57097,NaN,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...,NaN
1,tt0012349,movie,The Kid,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,Drama,Family,https://www.imdb.com/title/tt0012349,8.3,112377,NaN,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...,NaN
2,tt0013442,movie,Nosferatu,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,Horror,NaN,https://www.imdb.com/title/tt0013442,7.9,88440,NaN,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...,NaN

### So we have to write it back to the variable dataframe

In [19]:
df = df.rename(columns={'startYear': 'start_year'})
df.head(3)

,tconst,titleType,primaryTitle,originalTitle,isAdult,start_year,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url,new_metascore
0,tt0010323,movie,The Cabinet of Dr. Caligari,Das Cabinet des Dr. Caligari,0,1920,NaN,76.0,"Fantasy,Horror,Mystery",Fantasy,Horror,Mystery,https://www.imdb.com/title/tt0010323,8.1,57097,NaN,Germany,NaN,Black and White,"$18,000",NaN,"$8,811","$8,811",You must become Caligari.,"Hypnotist Dr. Caligari uses a somnambulist, Ce...",https://m.media-amazon.com/images/M/MV5BNWJiNG...,NaN
1,tt0012349,movie,The Kid,The Kid,0,1921,NaN,68.0,"Comedy,Drama,Family",Comedy,Drama,Family,https://www.imdb.com/title/tt0012349,8.3,112377,NaN,USA,NaN,Black and White,"$250,000",NaN,NaN,"$26,916",This is the great film he has been working on ...,"The Tramp cares for an abandoned child, but ev...",https://m.media-amazon.com/images/M/MV5BZjhhMT...,NaN
2,tt0013442,movie,Nosferatu,"Nosferatu, eine Symphonie des Grauens",0,1922,NaN,94.0,"Fantasy,Horror",Fantasy,Horror,NaN,https://www.imdb.com/title/tt0013442,7.9,88440,NaN,Germany,NaN,Black and White,NaN,NaN,NaN,"$19,054",A thrilling mystery masterpiece - a chilling p...,Vampire Count Orlok expresses interest in a ne...,https://m.media-amazon.com/images/M/MV5BMTAxYj...,NaN

### What shall we do with null values? We can use .fillna() to give them a specific value.

In [20]:
df['endYear'] = df['endYear'].fillna(-1)

### Sorting your dataframe is also important. This can be done with `.sort_values()` Don't forget to inspect additional arguments of this function using `Shift + Tab` inside the function.

### 1. Let's first sort the dataframe on `originalTitle` using argument `by`

In [21]:
df.sort_values(by='originalTitle')

,tconst,titleType,primaryTitle,originalTitle,isAdult,start_year,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url,new_metascore
4928,tt2614684,movie,'71,'71,0,2014,-1.0,99.0,"Action,Crime,Drama",Action,Crime,Drama,https://www.imdb.com/title/tt2614684,7.2,50947,83.0,UK,English,Color,NaN,"$55,761,","$1,270,847","$3,062,178",NaN,"In 1971, a young and disorientated British sol...",https://m.media-amazon.com/images/M/MV5BMTg1Nj...,8.3
661,tt0090555,movie,Crocodile Dundee,'Crocodile' Dundee,0,1986,-1.0,97.0,"Action,Adventure,Comedy",Action,Adventure,Comedy,https://www.imdb.com/title/tt0090555,6.6,92299,62.0,Australia,English,Color,"$8,800,000","$8,038,855,","$174,803,506","$328,203,506",The Wizard of Auz hits The Big Apple!,An American reporter goes to the Australian ou...,https://m.media-amazon.com/images/M/MV5BZjNlMT...,6.2
715,tt0092493,movie,Crocodile Dundee II,'Crocodile' Dundee II,0,1988,-1.0,108.0,"Action,Adventure,Comedy",Action,Adventure,Comedy,https://www.imdb.com/title/tt0092493,5.7,53146,41.0,Australia,English,Color,"$14,000,000","$24,462,976,","$109,306,210","$239,606,210",The World's Favorite Adventurer Is Back For More!,Australian outback expert protects his New Yor...,https://m.media-amazon.com/images/M/MV5BMzkxYT...,4.1
3507,tt1022603,movie,500 Days of Summer,(500) Days of Summer,0,2009,-1.0,95.0,"Comedy,Drama,Romance",Comedy,Drama,Romance,https://www.imdb.com/title/tt1022603,7.7,470495,76.0,USA,English,Color,"$7,500,000","$834,501,","$32,391,374","$60,722,734",It was almost like falling in love.,An offbeat romantic comedy about a woman who d...,https://m.media-amazon.com/images/M/MV5BMTk5Mj...,7.6
716,tt0092494,movie,*batteries not included,*batteries not included,0,1987,-1.0,106.0,"Comedy,Family,Fantasy",Comedy,Family,Fantasy,https://www.imdb.com/title/tt0092494,6.7,31354,54.0,USA,English,Color,"$25,000,000","$3,326,530,","$32,945,797","$65,088,797",Five ordinary people needed a miracle. Then on...,Aliens help a feisty old New York couple in th...,https://m.media-amazon.com/images/M/MV5BM2JlMD...,5.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3342,tt0856288,movie,Inside,À l'intérieur,0,2007,-1.0,82.0,Horror,Horror,NaN,NaN,https://www.imdb.com/title/tt0856288,6.8,37328,NaN,France,French,Color,"EUR2,400,000",NaN,NaN,"$792,184",Terror Comes Calling.,"Four months after the death of her husband, a ...",https://m.media-amazon.com/images/M/MV5BNTgyOD...,NaN
2707,tt0402022,movie,Æon Flux,Æon Flux,0,2005,-1.0,93.0,"Action,Adventure,Sci-Fi",Action,Adventure,Sci-Fi,https://www.imdb.com/title/tt0402022,5.5,123761,36.0,USA,English,Color,"$62,000,000","$12,661,112,","$25,874,337","$53,321,673",Perfect Future Shock,Aeon Flux is a mysterious assassin working for...,https://m.media-amazon.com/images/M/MV5BMTc2Mz...,3.6
5686,tt7134908,tvSeries,Elite,Élite,0,2018,-1.0,60.0,"Crime,Drama,Thriller",Crime,Drama,Thriller,https://www.imdb.com/title/tt7134908,7.6,46199,NaN,Spain,Spanish,Color,NaN,NaN,NaN,NaN,"""Til death do us part.""",When three working-class teenagers begin atten...,https://m.media-amazon.com/images/M/MV5BYWJhMW...,NaN
1963,tt0235198,movie,Audition,Ôdishon,0,1999,-1.0,115.0,"Drama,Horror,Mystery",Drama,Horror,Mystery,https://www.imdb.com/title/tt0235198,7.2,72515,69.0,Japan,Japanese,Color,NaN,NaN,"$131,296","$359,853",She always gets a part,A widower takes an offer to screen girls at a ...,https://m.media-amazon.com/images/M/MV5BOWYzZj...,6.9
4677,tt2140203,movie,Wolf Children,Ôkami kodomo no Ame to Yuki,0,2012,-1.0,117.0,"Animation,Drama,Fantasy",Animation,Drama,Fantasy,https://www.imdb.com/title/tt2140203,8.1,38470,71.0,Japan,Japanese,Color,NaN,NaN,NaN,"$55,060,661",Love wildly,After her werewolf lover unexpectedly dies in ...,https://m.media-amazon.com/images/M/MV5BYzQxND...,7.1

### 2. Now sort the whole list on title in descending order, using `ascending=False`

In [22]:
df.sort_values(by='originalTitle', ascending=False)

,tconst,titleType,primaryTitle,originalTitle,isAdult,start_year,endYear,runtimeMinutes,genres,genre1,genre2,genre3,url,averageRating,numVotes,metascore,country,primary_language,color,budget,opening_weekend_usa,gross_usa,cumulative_worldwide,tagline,summary,image_url,new_metascore
4677,tt2140203,movie,Wolf Children,Ôkami kodomo no Ame to Yuki,0,2012,-1.0,117.0,"Animation,Drama,Fantasy",Animation,Drama,Fantasy,https://www.imdb.com/title/tt2140203,8.1,38470,71.0,Japan,Japanese,Color,NaN,NaN,NaN,"$55,060,661",Love wildly,After her werewolf lover unexpectedly dies in ...,https://m.media-amazon.com/images/M/MV5BYzQxND...,7.1
1963,tt0235198,movie,Audition,Ôdishon,0,1999,-1.0,115.0,"Drama,Horror,Mystery",Drama,Horror,Mystery,https://www.imdb.com/title/tt0235198,7.2,72515,69.0,Japan,Japanese,Color,NaN,NaN,"$131,296","$359,853",She always gets a part,A widower takes an offer to screen girls at a ...,https://m.media-amazon.com/images/M/MV5BOWYzZj...,6.9
5686,tt7134908,tvSeries,Elite,Élite,0,2018,-1.0,60.0,"Crime,Drama,Thriller",Crime,Drama,Thriller,https://www.imdb.com/title/tt7134908,7.6,46199,NaN,Spain,Spanish,Color,NaN,NaN,NaN,NaN,"""Til death do us part.""",When three working-class teenagers begin atten...,https://m.media-amazon.com/images/M/MV5BYWJhMW...,NaN
2707,tt0402022,movie,Æon Flux,Æon Flux,0,2005,-1.0,93.0,"Action,Adventure,Sci-Fi",Action,Adventure,Sci-Fi,https://www.imdb.com/title/tt0402022,5.5,123761,36.0,USA,English,Color,"$62,000,000","$12,661,112,","$25,874,337","$53,321,673",Perfect Future Shock,Aeon Flux is a mysterious assassin working for...,https://m.media-amazon.com/images/M/MV5BMTc2Mz...,3.6
3342,tt0856288,movie,Inside,À l'intérieur,0,2007,-1.0,82.0,Horror,Horror,NaN,NaN,https://www.imdb.com/title/tt0856288,6.8,37328,NaN,France,French,Color,"EUR2,400,000",NaN,NaN,"$792,184",Terror Comes Calling.,"Four months after the death of her husband, a ...",https://m.media-amazon.com/images/M/MV5BNTgyOD...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,tt0092494,movie,*batteries not included,*batteries not included,0,1987,-1.0,106.0,"Comedy,Family,Fantasy",Comedy,Family,Fantasy,https://www.imdb.com/title/tt0092494,6.7,31354,54.0,USA,English,Color,"$25,000,000","$3,326,530,","$32,945,797","$65,088,797",Five ordinary people needed a miracle. Then on...,Aliens help a feisty old New York couple in th...,https://m.media-amazon.com/images/M/MV5BM2JlMD...,5.4
3507,tt1022603,movie,500 Days of Summer,(500) Days of Summer,0,2009,-1.0,95.0,"Comedy,Drama,Romance",Comedy,Drama,Romance,https://www.imdb.com/title/tt1022603,7.7,470495,76.0,USA,English,Color,"$7,500,000","$834,501,","$32,391,374","$60,722,734",It was almost like falling in love.,An offbeat romantic comedy about a woman who d...,https://m.media-amazon.com/images/M/MV5BMTk5Mj...,7.6
715,tt0092493,movie,Crocodile Dundee II,'Crocodile' Dundee II,0,1988,-1.0,108.0,"Action,Adventure,Comedy",Action,Adventure,Comedy,https://www.imdb.com/title/tt0092493,5.7,53146,41.0,Australia,English,Color,"$14,000,000","$24,462,976,","$109,306,210","$239,606,210",The World's Favorite Adventurer Is Back For More!,Australian outback expert protects his New Yor...,https://m.media-amazon.com/images/M/MV5BMzkxYT...,4.1
661,tt0090555,movie,Crocodile Dundee,'Crocodile' Dundee,0,1986,-1.0,97.0,"Action,Adventure,Comedy",Action,Adventure,Comedy,https://www.imdb.com/title/tt0090555,6.6,92299,62.0,Australia,English,Color,"$8,800,000","$8,038,855,","$174,803,506","$328,203,506",The Wizard of Auz hits The Big Apple!,An American reporter goes to the Australian ou...,https://m.media-amazon.com/images/M/MV5BZjNlMT...,6.2
4928,tt2614684,movie,'71,'71,0,2014,-1.0,99.0,"Action,Crime,Drama",Action,Crime,Drama,https://www.imdb.com/title/tt2614684,7.2,50947,83.0,UK,English,Color,NaN,"$55,761,","$1,270,847","$3,062,178",NaN,"In 1971, a young and disorientated British sol...",https://m.media-amazon.com/images/M/MV5BMTg1Nj...,8.3

### 3. Or we can sort on multiple columns. Now we need to use lists:

In [24]:
df.sort_values(by=['startYear', 'runtimeMinutes'], ascending=[False, True])

KeyError: 'startYear'