# Joining dataframes

### In SQL we use inner joins, left joins, and outer joins to connect 2 tables to eachother. <br>The join to connect the 2 tables is made on a id or column that can be found in both datasets

### In pandas the easiest way to join 2 tables is to use `df.merge()`
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html

### Let's create some example data

In [2]:
import pandas as pd

movie_data = [
    ['Pulp Fiction', 90],
    ['James Bond', 120],
    ['Titanic', 115],
]

movies = pd.DataFrame(movie_data, columns=['title', 'runtime'])

actor_data = [
    ['Pulp Fiction', 'John Travolta'],
    ['Pulp Fiction', 'Samuel L. Jackson'],
    ['James Bond', 'Sean Connery'],
    ['Terminator', 'Arnold Schwarzenegger'],
]

actors = pd.DataFrame(actor_data, columns=['title', 'name'])

In [ ]:
movies

          title  runtime
0  Pulp Fiction       90
1    James Bond      120
2       Titanic      115

In [ ]:
actors

          title                   name
0  Pulp Fiction          John Travolta
1  Pulp Fiction      Samuel L. Jackson
2    James Bond           Sean Connery
3    Terminator  Arnold Schwarzenegger

### Let's try an inner join and see what the result of the inner join looks like

In [3]:
df_inner = movies.merge(actors, how='inner',on='title')
df_inner

          title  runtime               name
0  Pulp Fiction       90      John Travolta
1  Pulp Fiction       90  Samuel L. Jackson
2    James Bond      120       Sean Connery

### FYI: instead of using a dataframe function, you can also use the general pandas function pd.merge()

In [4]:
pd.merge(movies, actors, how='inner', on='title')

          title  runtime               name
0  Pulp Fiction       90      John Travolta
1  Pulp Fiction       90  Samuel L. Jackson
2    James Bond      120       Sean Connery

### Let's do a left join from movies to actors and see what that result looks like

In [6]:
df_left = pd.merge(movies, actors, how='left', on='title')
df_left

          title  runtime               name
0  Pulp Fiction       90      John Travolta
1  Pulp Fiction       90  Samuel L. Jackson
2    James Bond      120       Sean Connery
3       Titanic      115                NaN

### And let's do the outer join. All the syntax is quite similar

In [8]:
df_outer = pd.merge(movies, actors, how='outer', on='title')
df_outer

          title  runtime                   name
0    James Bond    120.0           Sean Connery
1  Pulp Fiction     90.0          John Travolta
2  Pulp Fiction     90.0      Samuel L. Jackson
3    Terminator      NaN  Arnold Schwarzenegger
4       Titanic    115.0                    NaN